name: 2 - Merge to Develop

on:
  push: 
    branches:
      - 'develop'

permissions:
  pull-requests: write

jobs:
    pushing_to_develop:
        runs-on: ubuntu-latest
        steps:
            - name: Just testing
              run: echo "Hello there! More actions coming soon."
              